# Generated by Django 6.1 on 2026-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pictures/profilepic.png", upload_to="profile_pictures"
            ),
        ),
    ]
