# Generated by Django 6.1 on 2026-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTouJqFpAlcO1WK_3LKKl64xaEiQkjgx5YAv6pcM8l2sg&s=10",
                max_length=500,
            ),
        ),
    ]
