# Generated by Django 6.1 on 2026-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="added_on",
            field=models.DateField(auto_now=True),
        ),
    ]
