# Generated by Django 6.1 on 2026-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_item_myapp_item_user_na_18bfbe_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
